---
- name: start app in docker
  hosts: all
  become: true
  gather_facts: false

  vars:
    default_container_name: otus-reddit
    default_container_image: sun8877777/otus-reddit:1.0

  tasks:
  - name: Pull default Docker image
    community.docker.docker_image:
      name: "{{ default_container_image }}"
      source: pull

  - name: Create default containers
    community.docker.docker_container:
      name: "{{ default_container_name }}"
      image: "{{ default_container_image }}"
      state: started
      restart_policy: on-failure
      ports:
      - "9292:9292"
