version: "3.3"
services:

  post_db:
    env_file:
      - .env
    image: mongo:${VERSION_MONGO}
    volumes:
      - ${VOLUME_MONGO}:/data/db
    networks:
       back_net:
        aliases:
          - comment_db
          - post_db
  ui:
    env_file:
        - .env
    image: ${USERNAME}/ui:${VERSION}
    ports:
      - 9292:9292/tcp
    networks:
      - front_net
    logging:
      driver: "fluentd"
      options:
      fluentd-address: localhost:24224
tag: service.ui

  post:
    env_file:
        - .env
    image: ${USERNAME}/post:${VERSION}
    networks:
      - front_net
      - back_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post

  comment:
    env_file:
        - .env
    image: ${USERNAME}/comment:${VERSION}
    networks:
      - front_net
      - back_net

  prometheus:
    image: ${USERNAME}/prometheus:1.3.7
    ports:
      - '9090:9090'
    volumes:
    - prometheus_data:/prometheus
    command: # Передаем доп параметры в командной строке
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d' # Задаем время хранения метрик в 1 день
    networks:
      - front_net
      - back_net

  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    ports:
      - '9100:9100'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - front_net
      - back_net

  mongodb_exporter:
    image: percona/mongodb_exporter:0.34.0
    environment:
      - MONGODB_URI=mongodb://post_db:27017
    ports:
      - '9216:9216'
    networks:
      - front_net
      - back_net
  blackbox-exporter:
    image: prom/blackbox-exporter:master
    hostname: 'blackbox_exporter'
    volumes:
      - blackbox_config:/config
    networks:
      - front_net
      - back_net
volumes:
  post_db:
  prometheus_data:
  blackbox_config:

networks:
  back_net:
  front_net:
