- hosts: master
  become: true
  gather_facts: false
  tasks:
    - name: Get the token for joining the worker nodes
      become_user: ubuntu
      command: kubeadm token create  --print-join-command
      register: kubernetes_join_command

    - name: show join-command details
      debug: msg="{{ kubernetes_join_command.stdout }}"

    - name: Copy join command to local file.
      local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777

- hosts: workers
  become: true
  gather_facts: true
  tasks:
    - name: Copy join command
      copy:
        src: /tmp/kubernetes_join_command
        dest: /tmp/kubernetes_join_command
        mode: 0777
      become_user: ubuntu

    - name: Join workers node
      command: sh /tmp/kubernetes_join_command
