version: "3.3"
services:
  ui:
    container_name: svc-ui
    volumes:
      - ui_volume:/app
    command: [ "puma", "--debug", "-w", "2" ]

  post:
    container_name: svc-post
    volumes:
      - post_volume:/app

  comment:
    container_name: svc-comment
    volumes:
      - comment_volume:/app
    command: [ "puma", "--debug", "-w", "2" ]

volumes:
  ui_volume:
  post_volume:
  comment_volume:
