version: "3.3"
services:

  post_db:
    env_file:
      - .env
    image: mongo:${VERSION_MONGO}
    volumes:
      - ${VOLUME_MONGO}:/data/db
    networks:
       back_net:
        aliases:
          - comment_db
          - post_db
  ui:
    env_file:
        - .env
    build: ./ui
    image: ${USERNAME}/ui:${VERSION}
    ports:
      - 9292:9292/tcp
    networks:
      - front_net

  post:
    env_file:
        - .env
    build: ./post-py
    image: ${USERNAME}/post:${VERSION}
    networks:
      - front_net
      - back_net

  comment:
    env_file:
        - .env
    build: ./comment
    image: ${USERNAME}/comment:${VERSION}
    networks:
      - front_net
      - back_net

volumes:
  post_db:

networks:
  back_net:
  front_net:
